FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Necesario para que Clerk funcione durante la compilación
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_cHJlc2VudC1sb2JzdGVyLTMzLmNsZXJrLmFjY291bnRzLmRldiQ"
ENV NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL=/dashboard
ENV NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL=/dashboard
ENV NEXT_PUBLIC_CLERK_SIGN_OUT_URL=/

RUN npx prisma generate
RUN npm run build

FROM node:18-alpine AS runner
WORKDIR /app

# Copiar archivos necesarios
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

# Variables de entorno para runtime
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm install --production
CMD ["npm", "start"]