FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1



ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_cHJlc2VudC1sb2JzdGVyLTMzLmNsZXJrLmFjY291bnRzLmRldiQ"
ENV CLERK_SECRET_KEY="sk_test_7ErY1VEyWh6rZXS2YBN4Zm4shJbkt9KF1gLfoTqvxX"


ENV NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL=/dashboard
ENV NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL=/dashboard
ENV NEXT_PUBLIC_CLERK_SIGN_OUT_URL=/



ENV GOOGLE_CLOUD_PROJECT_ID="gym-app-454921"
ENV GOOGLE_CLOUD_BUCKET_NAME="gym-app-profile-pics"

RUN npx prisma generate

RUN npm run build

FROM node:18-alpine AS runner
WORKDIR /app
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./

RUN npm install --production
CMD ["npm", "start"]